# Generated by Django 5.1.7 on 2025-03-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cause', models.TextField()),
                ('symptoms', models.JSONField(default=list)),
                ('prevention', models.JSONField(default=list)),
                ('solution', models.CharField(max_length=1000)),
                ('link', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='disease-info/')),
            ],
        ),
    ]
