# Generated by Django 5.1.7 on 2025-03-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseaseinfo',
            name='link',
            field=models.CharField(max_length=1000),
        ),
    ]
